"""Meltano source adapter — compile-time only."""

from __future__ import annotations

from dataplatformos.compiler.artifacts import GeneratedArtifact
from dataplatformos.compiler.model import Project, safe_name


def compile_meltano(project: Project) -> list[GeneratedArtifact]:
    artifacts: list[GeneratedArtifact] = []
    for pipeline in project.pipelines:
        for step in pipeline.steps:
            source = step.source
            connector = source.get("connector") or ""
            if not connector.startswith("meltano."):
                continue

            tap = connector.split(".", 1)[-1]
            name = safe_name(pipeline.id)
            landing = source.get("landingSpace")
            space = project.landing_spaces.get(landing) if landing else None
            storage = space.storage_ref if space else None

            meltano_yml = f"""# Generated by dataplatformos
version: 1
project_id: {name}
default_environment: prod
environments:
  - name: prod
plugins:
  extractors:
    - name: {tap}
      variant: meltanolabs
      pip_url: meltanolabs-{tap}
      config:
        # connection_ref: {source.get("connection_ref")}
        # pattern: {source.get("pattern")}
        # incremental_key: {source.get("incremental_key")}
  loaders:
    - name: target-jsonl
      variant: andyh1203
      pip_url: target-jsonl
      config:
        destination_path: ${{LANDING_PATH:-./landing}}
"""
            if storage:
                meltano_yml += f"\n# platform landing space: {landing} -> {storage}\n"

            artifacts.append(
                GeneratedArtifact(
                    relative_path=f"meltano/{name}/meltano.yml",
                    content=meltano_yml,
                    kind="meltano",
                )
            )
            artifacts.append(
                GeneratedArtifact(
                    relative_path=f"meltano/{name}/README.md",
                    content=(
                        f"# Meltano project for `{pipeline.id}`\n\n"
                        f"Step: `{step.id}`\n"
                        f"Landing mode: `{space.mode if space else 'n/a'}`\n"
                    ),
                    kind="meltano_readme",
                )
            )
    return artifacts
