"""dbt project generator."""

from __future__ import annotations

import json
from collections import defaultdict

from dataplatformos.compiler.artifacts import GeneratedArtifact
from dataplatformos.compiler.model import Project, safe_name


def generate_dbt_projects(project: Project) -> list[GeneratedArtifact]:
    """Group dbt steps by transform.dbt.project and emit minimal dbt projects."""
    by_project: dict[str, list] = defaultdict(list)

    for pipeline in project.pipelines:
        for step in pipeline.steps:
            if step.engine != "dbt":
                continue
            dbt = step.transform.get("dbt") or {}
            name = dbt.get("project") or f"{safe_name(pipeline.id)}_dbt"
            by_project[name].append((pipeline, step))

    artifacts: list[GeneratedArtifact] = []
    for project_name, items in by_project.items():
        artifacts.append(
            GeneratedArtifact(
                relative_path=f"dbt/{project_name}/dbt_project.yml",
                content=(
                    f"name: {project_name}\n"
                    f"version: 1.0.0\n"
                    f"config-version: 2\n"
                    f"profile: dataplatformos\n"
                    f"model-paths: [models]\n"
                    f"models:\n"
                    f"  {project_name}:\n"
                    f"    +materialized: incremental\n"
                ),
                kind="dbt_project",
            )
        )
        artifacts.append(
            GeneratedArtifact(
                relative_path=f"dbt/{project_name}/profiles.yml.example",
                content=(
                    "dataplatformos:\n"
                    "  target: dev\n"
                    "  outputs:\n"
                    "    dev:\n"
                    "      type: duckdb\n"
                    "      path: local.duckdb\n"
                    "      threads: 4\n"
                ),
                kind="dbt_profile_example",
            )
        )

        schema_models: list[dict] = []
        for pipeline, step in items:
            select = (step.transform.get("dbt") or {}).get("select") or step.target.get(
                "object"
            )
            model_name = safe_name(str(select).split("/")[-1].replace(".sql", ""))
            zone = step.zone
            obj = step.target.get("object", model_name)
            sql = (
                f"-- Generated stub for {pipeline.id}.{step.id}\n"
                f"-- Target: {zone}.{obj}\n"
                f"-- Replace with real transform SQL or keep project models in sync.\n"
                f"select 1 as _compiled_stub\n"
            )
            ref = step.transform.get("ref")
            if ref and str(ref).endswith(".sql"):
                rel = f"dbt/{project_name}/{ref}"
            else:
                rel = f"dbt/{project_name}/models/{zone}/{model_name}.sql"
            if not rel.endswith(".sql"):
                rel = f"{rel}.sql"
            artifacts.append(
                GeneratedArtifact(relative_path=rel, content=sql, kind="dbt_model")
            )

            cols = []
            cref = step.quality.get("contract_ref")
            if cref:
                for contract in project.contracts.values():
                    if contract.path.name in cref or cref.endswith(contract.path.name):
                        for attr in (contract.raw.get("spec") or {}).get("attributes") or []:
                            cols.append(
                                {"name": attr["name"], "description": attr.get("type", "")}
                            )
            schema_models.append(
                {
                    "name": model_name,
                    "description": f"{pipeline.id} / {step.id} → {zone}.{obj}",
                    "columns": cols,
                }
            )

        artifacts.append(
            GeneratedArtifact(
                relative_path=f"dbt/{project_name}/models/schema.yml",
                content=_dump_schema_yml(schema_models),
                kind="dbt_schema",
            )
        )
        artifacts.append(
            GeneratedArtifact(
                relative_path=f"dbt/{project_name}/README.md",
                content=(
                    f"# {project_name}\n\n"
                    f"Generated by dataplatformos from segment `{project.segment_id}`.\n"
                ),
                kind="dbt_readme",
            )
        )

    return artifacts


def _dump_schema_yml(models: list[dict]) -> str:
    lines = ["version: 2", "models:"]
    for m in models:
        lines.append(f"  - name: {m['name']}")
        desc = m.get("description") or ""
        lines.append(f"    description: {json.dumps(desc)}")
        cols = m.get("columns") or []
        if cols:
            lines.append("    columns:")
            for c in cols:
                lines.append(f"      - name: {c['name']}")
                if c.get("description"):
                    lines.append(f"        description: {json.dumps(c['description'])}")
    return "\n".join(lines) + "\n"
