"""Human-readable lineage docs from the compiled project graph."""

from __future__ import annotations

from dataplatformos.compiler.artifacts import GeneratedArtifact
from dataplatformos.compiler.model import Project


def generate_docs(project: Project) -> list[GeneratedArtifact]:
    lines = [
        f"# Segment: `{project.segment_id}`",
        "",
        "Generated by `pipeline docs generate` / compile.",
        "",
        "## Landing spaces",
        "",
    ]
    if project.landing_spaces:
        for space in project.landing_spaces.values():
            storage = space.storage_ref or "—"
            lines.append(f"- `{space.id}` — mode=`{space.mode}` storage=`{storage}`")
    else:
        lines.append("_None declared_")

    lines.extend(["", "## Pipelines", ""])
    for pipeline in project.pipelines:
        lines.append(f"### `{pipeline.id}`")
        lines.append("")
        lines.append("| Step | Zone | Engine | Trigger | Quality | Upstream → Downstream |")
        lines.append("|---|---|---|---|---|---|")
        for step in pipeline.steps:
            up = ", ".join(step.lineage.get("upstream") or []) or "—"
            down = ", ".join(step.lineage.get("downstream") or []) or "—"
            lines.append(
                f"| `{step.id}` | {step.zone} | {step.engine} | "
                f"{step.trigger.get('mode')} | {step.quality.get('on_failure')} | "
                f"{up} → {down} |"
            )
        lines.append("")

    lines.extend(["", "## Metrics", ""])
    if project.metrics:
        for metric in project.metrics.values():
            spec = metric.spec
            lines.append(
                f"- `{metric.id}` — **{spec.get('label')}** "
                f"({spec.get('type')}) model=`{spec.get('model', '—')}`"
            )
    else:
        lines.append("_None_")

    lines.extend(["", "## Data products", ""])
    if project.products:
        for product in project.products.values():
            spec = product.spec
            cert = (spec.get("certification") or {}).get("status")
            lines.append(
                f"- `{product.id}` — **{spec.get('name')}** "
                f"({spec.get('productType')}, {cert}) "
                f"owner=`{spec.get('owningDomain')}`"
            )
    else:
        lines.append("_None_")

    lines.extend(
        [
            "",
            "## Mermaid",
            "",
            "```mermaid",
            "flowchart LR",
        ]
    )
    for pipeline in project.pipelines:
        for step in pipeline.steps:
            node = f"{pipeline.id}/{step.id}".replace(".", "_")
            label = f"{step.id}\\n{step.zone}"
            lines.append(f'  {node}["{label}"]')
            for up in step.lineage.get("upstream") or []:
                unode = up.replace(".", "_")
                lines.append(f'  {unode}["{up}"] --> {node}')
            for down in step.lineage.get("downstream") or []:
                dnode = down.replace(".", "_")
                lines.append(f'  {node} --> {dnode}["{down}"]')
    lines.append("```")
    lines.append("")

    return [
        GeneratedArtifact(
            relative_path="docs/index.md",
            content="\n".join(lines),
            kind="docs",
        )
    ]
